project:
  type: website

website:
  title: "Bioinformatica"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pipaber?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/piero-palacios-bernuy-30209087/
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

comments: 
  giscus:
    repo: pipaber/Bioinformatica 

